// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzGSa3_obfm6GYz1iWwfw6fvbeytFrVr4',
    appId: '1:788343354933:web:2ae4ac6358964855c9e37c',
    messagingSenderId: '788343354933',
    projectId: 'wisy-7597f',
    authDomain: 'wisy-7597f.firebaseapp.com',
    storageBucket: 'wisy-7597f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYW6mAZTqrE9p42evv6OYTpbB9Wc6WUFg',
    appId: '1:788343354933:android:6d61dc659071c376c9e37c',
    messagingSenderId: '788343354933',
    projectId: 'wisy-7597f',
    storageBucket: 'wisy-7597f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rnnz6WB-PY4wNvWE5c7VCGZxu4sMIsM',
    appId: '1:788343354933:ios:b01d9773ae2c0de0c9e37c',
    messagingSenderId: '788343354933',
    projectId: 'wisy-7597f',
    storageBucket: 'wisy-7597f.appspot.com',
    iosBundleId: 'com.example.wisyPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rnnz6WB-PY4wNvWE5c7VCGZxu4sMIsM',
    appId: '1:788343354933:ios:6e8f682fe49cd4a2c9e37c',
    messagingSenderId: '788343354933',
    projectId: 'wisy-7597f',
    storageBucket: 'wisy-7597f.appspot.com',
    iosBundleId: 'com.example.wisyPhotoApp.RunnerTests',
  );
}
